#!/usr/bin/env python3
"""
Test fixtures for GitHub client tests
"""

org_payload = {
    "login": "google",
    "id": 1342004,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
    "url": "https://api.github.com/orgs/google",
    "repos_url": "https://api.github.com/orgs/google/repos",
    "events_url": "https://api.github.com/orgs/google/events",
    "hooks_url": "https://api.github.com/orgs/google/hooks",
    "issues_url": "https://api.github.com/orgs/google/issues",
    "members_url": "https://api.github.com/orgs/google/members{/member}",
    "public_members_url": "https://api.github.com/orgs/google/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
    "description": "Google ❤️ Open Source"
}

repos_payload = [
    {
        "id": 7697149,
        "node_id": "MDEwOlJlcG9zaXRvcnk3Njk3MTQ5",
        "name": "episodes.dart",
        "full_name": "google/episodes.dart",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
        },
        "html_url": "https://github.com/google/episodes.dart",
        "description": "A framework for timing performance",
        "fork": False,
        "url": "https://api.github.com/repos/google/episodes.dart",
        "created_at": "2012-09-23T01:44:56Z",
        "updated_at": "2019-09-23T11:53:58Z",
        "pushed_at": "2014-06-03T17:22:21Z",
        "git_url": "git://github.com/google/episodes.dart.git",
        "ssh_url": "git@github.com:google/episodes.dart.git",
        "clone_url": "https://github.com/google/episodes.dart.git",
        "size": 191,
        "stargazers_count": 12,
        "watchers_count": 12,
        "language": "Dart",
        "has_issues": True,
        "has_projects": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 22,
        "archived": False,
        "disabled": False,
        "open_issues_count": 0,
        "license": {
            "key": "bsd-3-clause",
            "name": "BSD 3-Clause \"New\" or \"Revised\" License",
            "spdx_id": "BSD-3-Clause",
            "url": "https://api.github.com/licenses/bsd-3-clause",
            "node_id": "MDc6TGljZW5zZW9uZQ=="
        },
        "forks": 22,
        "open_issues": 0,
        "watchers": 12,
        "default_branch": "master",
    },
    {
        "id": 8566972,
        "node_id": "MDEwOlJlcG9zaXRvcnk4NTY2OTcy",
        "name": "cpp-netlib",
        "full_name": "google/cpp-netlib",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
        },
        "html_url": "https://github.com/google/cpp-netlib",
        "description": "The C++ Network Library Project -- header-only, cross-platform, standards compliant networking library.",
        "fork": True,
        "url": "https://api.github.com/repos/google/cpp-netlib",
        "created_at": "2013-01-05T09:63:99Z",
        "updated_at": "2019-09-23T11:53:58Z",
        "pushed_at": "2014-06-03T17:22:21Z",
        "git_url": "git://github.com/google/cpp-netlib.git",
        "ssh_url": "git@github.com:google/cpp-netlib.git",
        "clone_url": "https://github.com/google/cpp-netlib.git",
        "size": 191,
        "stargazers_count": 12,
        "watchers_count": 12,
        "language": "C++",
        "has_issues": True,
        "has_projects": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 22,
        "archived": False,
        "disabled": False,
        "open_issues_count": 0,
        "license": {
            "key": "boost-1.0",
            "name": "Boost Software License 1.0",
            "spdx_id": "BSL-1.0",
            "url": "https://api.github.com/licenses/bsl-1.0",
            "node_id": "MDc6TGljZW5zZW9uZQ=="
        },
        "forks": 22,
        "open_issues": 0,
        "watchers": 12,
        "default_branch": "master",
    },
    {
        "id": 7776515,
        "node_id": "MDEwOlJlcG9zaXRvcnk3Nzc2NTE1",
        "name": "dagger",
        "full_name": "google/dagger",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
        },
        "html_url": "https://github.com/google/dagger",
        "description": "A fast dependency injector for Android and Java.",
        "fork": False,
        "url": "https://api.github.com/repos/google/dagger",
        "created_at": "2012-09-26T09:47:07Z",
        "updated_at": "2019-09-23T11:53:58Z",
        "pushed_at": "2014-06-03T17:22:21Z",
        "git_url": "git://github.com/google/dagger.git",
        "ssh_url": "git@github.com:google/dagger.git",
        "clone_url": "https://github.com/google/dagger.git",
        "size": 191,
        "stargazers_count": 12,
        "watchers_count": 12,
        "language": "Java",
        "has_issues": True,
        "has_projects": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 22,
        "archived": False,
        "disabled": False,
        "open_issues_count": 0,
        "license": {
            "key": "apache-2.0",
            "name": "Apache License 2.0",
            "spdx_id": "Apache-2.0",
            "url": "https://api.github.com/licenses/apache-2.0",
            "node_id": "MDc6TGljZW5zZW9uZQ=="
        },
        "forks": 22,
        "open_issues": 0,
        "watchers": 12,
        "default_branch": "master",
    },
    {
        "id": 7968347,
        "node_id": "MDEwOlJlcG9zaXRvcnk3OTY4MzQ3",
        "name": "ios-webkit-debug-proxy",
        "full_name": "google/ios-webkit-debug-proxy",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
        },
        "html_url": "https://github.com/google/ios-webkit-debug-proxy",
        "description": "A DevTools proxy (Chrome Remote Debugging Protocol) for iOS devices (Safari Remote Web Inspector).",
        "fork": True,
        "url": "https://api.github.com/repos/google/ios-webkit-debug-proxy",
        "created_at": "2012-10-08T07:58:34Z",
        "updated_at": "2019-09-23T11:53:58Z",
        "pushed_at": "2014-06-03T17:22:21Z",
        "git_url": "git://github.com/google/ios-webkit-debug-proxy.git",
        "ssh_url": "git@github.com:google/ios-webkit-debug-proxy.git",
        "clone_url": "https://github.com/google/ios-webkit-debug-proxy.git",
        "size": 191,
        "stargazers_count": 12,
        "watchers_count": 12,
        "language": "C",
        "has_issues": True,
        "has_projects": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 22,
        "archived": False,
        "disabled": False,
        "open_issues_count": 0,
        "license": {
            "key": "bsd-2-clause",
            "name": "BSD 2-Clause \"Simplified\" License",
            "spdx_id": "BSD-2-Clause",
            "url": "https://api.github.com/licenses/bsd-2-clause",
            "node_id": "MDc6TGljZW5zZW9uZQ=="
        },
        "forks": 22,
        "open_issues": 0,
        "watchers": 12,
        "default_branch": "master",
    },
    {
        "id": 11730342,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMTczMDM0Mg==",
        "name": "build2-toolchain",
        "full_name": "google/build2-toolchain",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
        },
        "html_url": "https://github.com/google/build2-toolchain",
        "description": "build2 toolchain",
        "fork": True,
        "url": "https://api.github.com/repos/google/build2-toolchain",
        "created_at": "2013-07-22T00:45:58Z",
        "updated_at": "2019-09-23T11:53:58Z",
        "pushed_at": "2014-06-03T17:22:21Z",
        "git_url": "git://github.com/google/build2-toolchain.git",
        "ssh_url": "git@github.com:google/build2-toolchain.git",
        "clone_url": "https://github.com/google/build2-toolchain.git",
        "size": 191,
        "stargazers_count": 12,
        "watchers_count": 12,
        "language": "C++",
        "has_issues": True,
        "has_projects": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 22,
        "archived": False,
        "disabled": False,
        "open_issues_count": 0,
        "license": {
            "key": "apache-2.0",
            "name": "Apache License 2.0",
            "spdx_id": "Apache-2.0",
            "url": "https://api.github.com/licenses/apache-2.0",
            "node_id": "MDc6TGljZW5zZW9uZQ=="
        },
        "forks": 22,
        "open_issues": 0,
        "watchers": 12,
        "default_branch": "master",
    }
]

expected_repos = [
    "episodes.dart",
    "cpp-netlib",
    "dagger",
    "ios-webkit-debug-proxy",
    "build2-toolchain"
]

apache2_repos = [
    "dagger",
    "build2-toolchain"
]