# Generated by Django 5.2.6 on 2025-09-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_rename_sender_id_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default='e030c9ad-37ec-42a0-a248-995cad95fee6', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.conversation'),
            preserve_default=False,
        ),
    ]
