# Generated by Django 5.2.6 on 2025-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
