# Generated by Django 5.2.6 on 2025-09-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_customjwt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
